services:
  server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_IP={{POSTGRES_IP}}
      - POSTGRES_PORT={{POSTGRES_PORT}}
      - POSTGRES_USER={{POSTGRES_USER}}
      - POSTGRES_PASSWORD={{POSTGRES_PASSWORD}}